myassignment/movie/urls.py
from django.conf.urls import url 
from movie import views
from django.urls import path 
from django.conf.urls.static import static

app_name = 'movie'

urlpatterns=[
    path('',views.HomePageView.as_view(), name='home'),
    path('movie-prod-country/',views.Api.movie_prod_country, name='movie-prod-country'),
    path('average-production-budget/',views.Api.average_production_budget, name='average-production-budget'),
    path('total-box-office/',views.Api.total_box_office, name='total-box-office'),
    path('total-box-year/',views.Api.total_box_year, name='total-box-year'),
    path('tikcet-sold-price/',views.Api.tikcet_sold_price, name='tikcet-sold-price'),
    path('release-per-year/',views.Api.release_per_year, name='release-per-year'),
    path('top-per-year/',views.Api.top_per_year, name='top-per-year'),
    path('ticket-sold/',views.Api.ticket_sold, name='ticket-sold'),
    path('top-dist-ms/',views.Api.top_dist_ms, name='top-dist-ms'),
    path('top-genre-ms/',views.Api.top_genre_ms, name='top-genre-ms'),
    path('top-mpaa-ms/',views.Api.top_mpaa_ms, name='top-mpaa-ms'),
    path('top-source-ms/',views.Api.top_source_ms, name='top-source-ms'),
    path('top-method-ms/',views.Api.top_method_ms, name='top-method-ms'),
    path('top-creative-ms/',views.Api.top_creative_ms, name='top-creative-ms'),
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
]

myassignment/myassignment/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from movie import views
from myassignment.settings import DEBUG, STATIC_URL, STATIC_DIR, MEDIA_URL,MEDIA_ROOT
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^special/',views.special,name='special'),
    url(r'^movie/',include('movie.urls')),
    url(r'^logout/$',views.user_logout, name='logout'),
]

if DEBUG:
    urlpatterns += static(MEDIA_URL, document_root = MEDIA_ROOT)

myassignment/movie/models.py
from django.db import models


from django.db import models
from django.contrib.auth.models import User

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    age = models.TextField (blank=True)
    sex = models.TextField (blank=True)
    hobby = models.TextField (blank=True)

    def __str__(self):
        return self.user.username

myassignment/movie/forms.py
from django import forms
from movie.models import UserProfileInfo
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','password','email')

class UserProfileInfoForm(forms.ModelForm):

    class Meta():
        model = UserProfileInfo
        fields = ('age', 'sex', 'hobby')

myassignment/movie/views.py
from django.shortcuts import render
from django.http import HttpResponse
from myassignment.settings import MEDIA_URL,MEDIA_ROOT
from django.conf.urls.static import static
from django.views.generic import TemplateView, View 

from movie.forms import UserForm, UserProfileInfoForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from movie.models import UserProfileInfo

import re
import csv
import numpy as np
import pandas as pd
import matplotlib as pl
pl.use('Agg')
import matplotlib.pyplot as plt
import seaborn as sb

class HomePageView(TemplateView):
    def get(self,request,**kwargs):
        return render(request, 'movie/index.html', context=None)

class Api(TemplateView):

    def movie_prod_country(request):

        def making_table(csv_file, column_start, column_end, name_list):
            dst = pd.read_csv(csv_file, header = None, index_col = False)
            dst = dst.iloc[:,column_start:column_end].values
            dst_movie = pd.DataFrame(dst, columns = [name_list])
    
            return dst_movie
        
        def spchar_removal(array, starting_column, name_list):
            Lrow = len(array)
            Lcol = len(array[0])
        
            current_row = 0
            current_column = starting_column
        
            while current_column < Lcol:
                current_row = 0
                while current_row < Lrow:
                    array[current_row, current_column] = re.sub(r",", "", array[current_row, current_column])
                    array[current_row, current_column] = re.sub(r"\$", "", array[current_row, current_column])
                    array[current_row, current_column] = re.sub(r"%", "", array[current_row, current_column])
                    current_row = current_row + 1
                
                current_column = current_column + 1
            
            dst_movie = pd.DataFrame(array, columns = [name_list])
        
            return dst_movie

        real_path = 'Movie Production Countries'
        csv_file = MEDIA_ROOT+'/data/'+ real_path +'.csv'
        name_list = ['Country', 'No. of Movies', 'Average Production Budget ($)', 'Total Worldwide Box Office ($)']
        country_prod = making_table(csv_file, 1, 5, name_list)

        country_prod = country_prod.drop(country_prod.index[15:])
        temp = country_prod.to_numpy()
        country_prod = spchar_removal(temp, 1, name_list)

        country_prod['No. of Movies'] = country_prod['No. of Movies'].astype(int)
        country_prod['Average Production Budget ($)'] = country_prod['Average Production Budget ($)'].astype(np.int64)
        country_prod['Total Worldwide Box Office ($)'] = country_prod['Total Worldwide Box Office ($)'].astype(np.int64)
        temp = []

        x = []
        temp = country_prod['Country'].to_numpy()
        x = np.append(temp, x)
        y1 = []
        temp = country_prod['No. of Movies'].to_numpy()
        y1 = np.append(temp, y1)


        plt.figure(figsize = (12, 8), dpi= 100)
        plt.bar(x, y1)
        plt.title('Number of Movies vs Country', fontsize = 14)
        plt.xlabel("Country", fontsize = 14)
        plt.ylabel("Number of Movies", color="black", fontsize = 14)
        plt.xticks(rotation = 90)

        plt.grid(True)
        plt.show()

        response = HttpResponse(content_type="image/jpeg")
        plt.savefig(response, format="png")
        return response

    def average_production_budget(request):

        def making_table(csv_file, column_start, column_end, name_list):
            dst = pd.read_csv(csv_file, header = None, index_col = False)
            dst = dst.iloc[:,column_start:column_end].values
            dst_movie = pd.DataFrame(dst, columns = [name_list])
    
            return dst_movie
        
        def spchar_removal(array, starting_column, name_list):
            Lrow = len(array)
            Lcol = len(array[0])
        
            current_row = 0
            current_column = starting_column
        
            while current_column < Lcol:
                current_row = 0
                while current_row < Lrow:
                    array[current_row, current_column] = re.sub(r",", "", array[current_row, current_column])
                    array[current_row, current_column] = re.sub(r"\$", "", array[current_row, current_column])
                    array[current_row, current_column] = re.sub(r"%", "", array[current_row, current_column])
                    current_row = current_row + 1
                
                current_column = current_column + 1
            
            dst_movie = pd.DataFrame(array, columns = [name_list])
        
            return dst_movie

        real_path = 'Movie Production Countries'
        csv_file = MEDIA_ROOT+'/data/'+ real_path +'.csv'
        name_list = ['Country', 'No. of Movies', 'Average Production Budget ($)', 'Total Worldwide Box Office ($)']
        country_prod = making_table(csv_file, 1, 5, name_list)

        country_prod = country_prod.drop(country_prod.index[15:])
        temp = country_prod.to_numpy()
        country_prod = spchar_removal(temp, 1, name_list)

        country_prod['No. of Movies'] = country_prod['No. of Movies'].astype(int)
        country_prod['Average Production Budget ($)'] = country_prod['Average Production Budget ($)'].astype(np.int64)
        country_prod['Total Worldwide Box Office ($)'] = country_prod['Total Worldwide Box Office ($)'].astype(np.int64)
        temp = []

        x = []
        temp = country_prod['Country'].to_numpy()
        x = np.append(temp, x)
        y1 = []
        temp = country_prod['Average Production Budget ($)'].to_numpy()
        y1 = np.append(temp, y1)

        plt.figure(figsize = (12, 8), dpi= 100)
        plt.plot(x, y1, color='red', marker='o', label = 'Average Production Budget')
        plt.title('Average Production Budget vs Country', fontsize = 14)
        plt.xlabel("Country", fontsize = 14)
        plt.ylabel("Average Production Budget ($)", color="black", fontsize = 14)
        plt.xticks(rotation = 90)

        plt.grid(True)
        plt.show()

        response = HttpResponse(content_type="image/jpeg")
        plt.savefig(response, format="png")
        return response

    def total_box_office(request):

        def making_table(csv_file, column_start, column_end, name_list):
            dst = pd.read_csv(csv_file, header = None, index_col = False)
            dst = dst.iloc[:,column_start:column_end].values
            dst_movie = pd.DataFrame(dst, columns = [name_list])
    
            return dst_movie
        
        def spchar_removal(array, starting_column, name_list):
            Lrow = len(array)
            Lcol = len(array[0])
        
            current_row = 0
            current_column = starting_column
        
            while current_column < Lcol:
                current_row = 0
                while current_row < Lrow:
                    array[current_row, current_column] = re.sub(r",", "", array[current_row, current_column])
                    array[current_row, current_column] = re.sub(r"\$", "", array[current_row, current_column])
                    array[current_row, current_column] = re.sub(r"%", "", array[current_row, current_column])
                    current_row = current_row + 1
                
                current_column = current_column + 1
            
            dst_movie = pd.DataFrame(array, columns = [name_list])
        
            return dst_movie

        real_path = 'Movie Production Countries'
        csv_file = MEDIA_ROOT+'/data/'+ real_path +'.csv'
        name_list = ['Country', 'No. of Movies', 'Average Production Budget ($)', 'Total Worldwide Box Office ($)']
        country_prod = making_table(csv_file, 1, 5, name_list)

        country_prod = country_prod.drop(country_prod.index[15:])
        temp = country_prod.to_numpy()
        country_prod = spchar_removal(temp, 1, name_list)

        country_prod['No. of Movies'] = country_prod['No. of Movies'].astype(int)
        country_prod['Average Production Budget ($)'] = country_prod['Average Production Budget ($)'].astype(np.int64)
        country_prod['Total Worldwide Box Office ($)'] = country_prod['Total Worldwide Box Office ($)'].astype(np.int64)
        temp = []

        x = []
        temp = country_prod['Country'].to_numpy()
        x = np.append(temp, x)
        y1 = []
        temp = country_prod['Total Worldwide Box Office ($)'].to_numpy()
        y1 = np.append(temp, y1)

        plt.figure(figsize = (12, 8), dpi= 100)
        plt.plot(x,y1, color='blue', marker='o', label = 'Total Worldwide Box Office')
        plt.title('Total Worldwide Box Office vs Country', fontsize = 14)
        plt.xlabel("Country", fontsize = 14)
        plt.ylabel("Total Worldwide Box Office ($)", color="black", fontsize = 14)
        plt.xticks(rotation = 90)

        plt.grid(True)
        plt.show()

        response = HttpResponse(content_type="image/jpeg")
        plt.savefig(response, format="png")
        return response

    def total_box_year(request):

        def making_table(csv_file, column_start, column_end, name_list):
            dst = pd.read_csv(csv_file, header = None, index_col = False)
            dst = dst.iloc[:,column_start:column_end].values
            dst_movie = pd.DataFrame(dst, columns = [name_list])
    
            return dst_movie
        
        def spchar_removal(array, starting_column, name_list):
            Lrow = len(array)
            Lcol = len(array[0])
        
            current_row = 0
            current_column = starting_column
        
            while current_column < Lcol:
                current_row = 0
                while current_row < Lrow:
                    array[current_row, current_column] = re.sub(r",", "", array[current_row, current_column])

myassignment/templates/movie/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script></head>
  <body style="background-color:#ADD8E6;">
    <nav class="navbar navbar-light" style="background-color:#4DB6AC;">
      <div class="container">
        <ul class="nav navbar-nav">
          {# Django Home Link / Admin Link / Register Link#}
          <li><a class="navbar-brand" href="{% url 'index' %}" style="background-color:#FFCC33;color:#000000;border-width:10px;border-color:#FFCC33;border-style:solid;border-spacing:30px;border-radius: 5px;">DJANGO</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}" style="background-color:#00F7FF;color:#000000;border-width:10px;border-color:#00F7FF;border-style:solid;border-spacing:30px;border-radius: 5px;">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'movie:register' %}" style="background-color:#62FF00;color:#000000;border-width:10px;border-color:#62FF00;border-style:solid;border-spacing:30px;border-radius: 5px;">Register</a></li>     
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}" style="background-color:	#CF9FFF;color:#000000;border-width:10px;border-color:	#CF9FFF;border-style:solid;border-spacing:30px;border-radius: 5px;">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'movie:user_login' %}" style="background-color:#CDFF15;color:#000000;border-width:10px;border-color:#CDFF15;border-style:solid;border-spacing:30px;border-radius: 5px;">Login</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
    {% block body_block %}
    {% endblock %}
  </body>
</html>

myassignment/templates/movie/index.html
{% extends "movie/base.html" %}
{% block body_block %}
<div style="text-align:center">
    <div class="container">
        <div class="jumbotron" style="background-color:#CBC3E3;">
          <h1>Welcome to Movie Trend Analysis from 1995 to 2021!</h1>
          {% if user.is_authenticated %}
              <h2>Hello there, {{ user.username }}!</h2>
          {% else %}
              <h2>Register or Login if you'd like to</h2>
          {% endif %} 
          <h3>
            <li><a class="navbar-link" href= "https://www.the-numbers.com/market/"> Data Source Click here</a></li>
          </h3>
          <h3></h3>
          <h4>
            Everytime when a button is clicked, kindly scroll back up/click on the "Back to Top" button at the bottom to see the data visualization.
          </h4>
        </div>
      </div>
    <a name="top"></a>
    <div class="container-fluid">
        <div class="row">
            <div class="col-3">
            <button onclick="getimage_mpc()">Movie Production in Different Countries</button>
            </div>
            <div class="col-9">
                <img id="matplotlib" width="1500">
            </div>
        <div>
        <div class="row">
            <div class="col-3">
            <button onclick="getimage_apb()">Average Production Budget in Different Countries</button>
            </div>
            <div class="col-9">
                <img id="matplotlib" width="1500">
            </div>
        <div>
        <div class="row">
            <div class="col-3">
            <button onclick="getimage_tbo()">Total Worldwide Box Office</button>
            </div>
            <div class="col-9">
                <img id="matplotlib" width="1500">
            </div>
        <div>
        <div class="row">
            <div class="col-3">
                <h1 style="color:#0055FF; text-align:center; font-size: 24px">
                    The United States was chosen for analysis from here onwards as it has the most movies produced with the highest total worldwide box office.
                </h1>
                <h1></h1>
            <button onclick="getimage_tbpy()">Total Box Office vs Year </button>
            </div>
            <div class="col-9">
                <img id="matplotlib" width="1500">
            </div>
        <div>
        <div class="row">
            <div class="col-3">
            <button onclick="getimage_tsp()">Ticket Sold and Average Ticket Price vs Year</button>
            </div>
            <div class="col-9">
                <img id="matplotlib" width="1500">
            </div>
        <div>
            <h1 style="color:#0055FF; text-align:center; font-size: 24px">
                Box office has a steady increase over the decades, the inflation is expected with movie success over the years. 
            </h1>
            <h1 style="color:#0055FF; text-align:center; font-size: 24px">
                Due to recent covid pandemic, ticket price plummeted sharply down the drain. Weirdly enough, the average price per ticket is not budging.
            </h1>    
            <h1></h1>
        <div class="row">
            <div class="col-3">
            <button onclick="getimage_rpy()">Movies Production Percentage by Different Production Distributor</button>
            </div>
            <div class="col-9">
                <img id="matplotlib" width="1500">
            </div>
            <h1 style="color:#0055FF; text-align:center; font-size: 24px">
                Surprisingly enough, other studios besides the BIG SIX are flourishing especially during the pandemic!
            </h1> 
            <h1></h1>
        <div>        
        <div class="row">
            <div class="col-3">
            <button onclick="getimage_tmvp()">Category Preferences in Annual Top Movies</button>
            </div>
            <div class="col-9">
                <img id="matplotlib" width="1500">
            </div>
            <h1 style="color:#0055FF; text-align:center; font-size: 24px">
               So it seems an original screenplay of a live action superhero adventure movie with a PG-13 rating is the best way to go! Walt Disney dominated the industry, no contest it seems.
            </h1> 
            <h1></h1>
        <div>        
        <div class="row">
            <div class="col-3">
            <button onclick="getimage_tss()">Ticket Sold and Total Sales for Top Movie Each Year</button>
            </div>
            <div class="col-9">
                <img id="matplotlib" width="1500">
            </div>
            <h1 style="color:#0055FF; text-align:center; font-size: 24px">
                Nothing much to see here, just a sad observation on the gradual increase in the ticket price. 
             </h1> 
             <h1 style="color:#0055FF; text-align:center; font-size: 24px">
                A much needed interruption from the pandemic to hopefully reset the price and halt the inflation, I guess...
             </h1>
             <h1></h1>
        <div>      
        <div class="row">
            <div class="col-3">
            <button onclick="getimage_tgms()">Market Share of Top Grossing Distributors</button>
            </div>
            <div class="col-9">
                <img id="matplotlib" width="1500">
            </div>
            <h1 style="color:#0055FF; text-align:center; font-size: 24px">
                It's safe to say the BIG SIX dominated the movie industry. What's scarier is that they are almost equal.
             </h1> 
             <h1></h1>
        <div>
        <div class="row">
            <div class="col-3">
            <button onclick="getimage_tgfms()">Market Share of Genres</button>
            </div>
            <div class="col-9">
                <img id="matplotlib" width="1500">
            </div>
            <h1 style="color:#0055FF; text-align:center; font-size: 24px">
                Adventure movies are most popular genre followed by Action movies, WHAT A SURPRISE.
             </h1> 
             <h1></h1>
        <div>
        <div class="row">
            <div class="col-3">
            <button onclick="getimage_tmpms()">Market Share of MPAA Ratings</button>
            </div>
                <div class="col-9">
                    <img id="matplotlib" width="1500">
                </div>
                <h1 style="color:#0055FF; text-align:center; font-size: 24px">
                    A successful movie must be rated PG-13, pressumably because of the wide array of audience.
                 </h1> 
                 <h1></h1>
            <div>
        <div class="row">
            <div class="col-3">
            <button onclick="getimage_tms()">Market Share of Movie Sources</button>
            </div>
                <div class="col-9">
                    <img id="matplotlib" width="1500">
                </div>
                <h1 style="color:#0055FF; text-align:center; font-size: 24px">
                    Original screenplay is the way to go. Personally, I ain't paying double to go through the same thing so give me something ORIGINAL.
                 </h1> 
                 <h1></h1>
            <div>
        <div class="row">
            <div class="col-3">
            <button onclick="getimage_tpms()">Market Share of Different Production Methods</button>
            </div>
                <div class="col-9">
                    <img id="matplotlib" width="1500">
                </div>
                <h1 style="color:#0055FF; text-align:center; font-size: 24px">
                    Well of course it's going to be live action movies, because they are more "pleasing" to the beholder's eyes if you catch my drift.
                 </h1> 
                 <h1></h1>
            <div>
        <div class="row">
            <div class="col-3">
            <button onclick="getimage_tcms()">Market Share of Different Creative Types</button>
            </div>
                <div class="col-9">
                    <img id="matplotlib" width="1500">
                </div>
                <h1 style="color:#0055FF; text-align:center; font-size: 24px">
                    There's a dreamer in all of us, and nothing hits more closely than a great contemporary fiction movie, need I say more?
                 </h1> 
                 <h1></h1>
            <div>
        <a href="#top" style="color:#A020F0; text-align:center; font-size: 24px">Back to top</a>                 
</div>
<script>
    // Make API calls
    function getimage_mpc() {
		fetch('{% url 'movie:movie-prod-country' %}')
		.then(res => res.blob())
		.then(data => {
            let imgURL = URL.createObjectURL(data)
            document.getElementById('matplotlib').src = imgURL
        })
	}

    function getimage_apb() {
		fetch('{% url 'movie:average-production-budget' %}')
		.then(res => res.blob())
		.then(data => {
            let imgURL = URL.createObjectURL(data)
            document.getElementById('matplotlib').src = imgURL
        })
	}

    function getimage_tbo() {
		fetch('{% url 'movie:total-box-office' %}')
		.then(res => res.blob())
		.then(data => {
            let imgURL = URL.createObjectURL(data)
            document.getElementById('matplotlib').src = imgURL
        })
	}

    function getimage_tbpy() {
		fetch('{% url 'movie:total-box-year' %}')
		.then(res => res.blob())
		.then(data => {
            let imgURL = URL.createObjectURL(data)
            document.getElementById('matplotlib').src = imgURL
        })
	}

    function getimage_tsp() {
		fetch('{% url 'movie:tikcet-sold-price' %}')
		.then(res => res.blob())
		.then(data => {
            let imgURL = URL.createObjectURL(data)
            document.getElementById('matplotlib').src = imgURL
        })
	}

    function getimage_rpy() {
		fetch('{% url 'movie:release-per-year' %}')
		.then(res => res.blob())
		.then(data => {
            let imgURL = URL.createObjectURL(data)
            document.getElementById('matplotlib').src = imgURL
        })
	}

    function getimage_tmvp() {
		fetch('{% url 'movie:top-per-year' %}')
		.then(res => res.blob())
		.then(data => {
            let imgURL = URL.createObjectURL(data)
            document.getElementById('matplotlib').src = imgURL
        })
	}

    function getimage_tss() {
		fetch('{% url 'movie:ticket-sold' %}')
		.then(res => res.blob())
		.then(data => {
            let imgURL = URL.createObjectURL(data)
            document.getElementById('matplotlib').src = imgURL
        })
	}

    function getimage_tgms() {
		fetch('{% url 'movie:top-dist-ms' %}')
		.then(res => res.blob())
		.then(data => {
            let imgURL = URL.createObjectURL(data)
            document.getElementById('matplotlib').src = imgURL
        })
	}

    function getimage_tgfms() {
		fetch('{% url 'movie:top-genre-ms' %}')
		.then(res => res.blob())
		.then(data => {
            let imgURL = URL.createObjectURL(data)
            document.getElementById('matplotlib').src = imgURL
        })
	}

    function getimage_tmpms() {
		fetch('{% url 'movie:top-mpaa-ms' %}')
		.then(res => res.blob())
		.then(data => {
            let imgURL = URL.createObjectURL(data)
            document.getElementById('matplotlib').src = imgURL
        })
	}

    function getimage_tms() {
		fetch('{% url 'movie:top-source-ms' %}')
		.then(res => res.blob())
		.then(data => {
            let imgURL = URL.createObjectURL(data)
            document.getElementById('matplotlib').src = imgURL
        })
	}

    function getimage_tpms() {
		fetch('{% url 'movie:top-method-ms' %}')
		.then(res => res.blob())
		.then(data => {
            let imgURL = URL.createObjectURL(data)
            document.getElementById('matplotlib').src = imgURL
        })
	}

    function getimage_tcms() {
		fetch('{% url 'movie:top-creative-ms' %}')
		.then(res => res.blob())
		.then(data => {
            let imgURL = URL.createObjectURL(data)
            document.getElementById('matplotlib').src = imgURL
        })
	}

</script>
{% endblock %}

myassignment/templates/movie/login.html
{% extends 'movie/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Login here :</h1>
          <form method="post" action="{% url 'movie:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">
          <label for="password">Password:</label>
          <input type="password" name="password" placeholder="Password">
          <input type="submit" name="" value="Login">
</form>
</div>
  </div>
{% endblock %}

myassignment/templates/movie/registration.html
{% extends "movie/base.html" %}
{% load static %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>
        <form enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <input type="submit" name="" value="Register">
        </form>
        
      {% endif %}
    </div>
  </div>
{% endblock %}